const segments={
 industrial:{priority:'PRIORITY 01',title:'Industrial & factory',hypothesis:'Shift-critical operations lose productivity when workers arrive late or transport cannot cover off-hours. SWVL can align fixed or dynamic routes to real demand and give operations live visibility.',signals:'New site · hiring surge · 24/7 shifts · remote facility · recurring transport complaints',buyers:'COO · HR Director · Facilities · Procurement · Transport Manager',proof:'Route optimization · multi-site dispatch · live tracking · consumption-based pricing'},
 callcenter:{priority:'PRIORITY 02',title:'Call centers',hypothesis:'Round-the-clock staffing depends on reliable transport across fluctuating shifts. SWVL can reduce late arrivals and administration with flexible booking, live tracking, and demand-aware operations.',signals:'New campaign · seat expansion · night shifts · high attrition · transport allowance review',buyers:'COO · People Director · Workforce Planning · Procurement · Site Director',proof:'Flexible booking · off-hours coverage · reporting · consumption-based pricing'},
 office:{priority:'PRIORITY 03',title:'Office & multi-site',hypothesis:'Hybrid schedules make fixed transport wasteful and difficult to manage. SWVL can match capacity to changing attendance while giving teams one booking and operations layer.',signals:'Return-to-office policy · HQ move · multi-branch expansion · parking constraint · ESG target',buyers:'CHRO · Workplace · Facilities · Sustainability · Procurement',proof:'Demand-responsive routes · rider app · admin dashboard · usage analytics'},
 education:{priority:'PRIORITY 04',title:'Education',hypothesis:'Schools and universities need safe, visible, schedule-reliable transport for distributed rider communities. SWVL can digitize booking, tracking, route design, and operational control.',signals:'New campus · enrollment growth · safety review · route redesign · parent experience initiative',buyers:'COO · Campus Operations · Student Affairs · Safety · Procurement',proof:'Fixed and dynamic routing · tracking · rider tools · managed fleet operations'},
 public:{priority:'PRIORITY 05',title:'Government & transit',hypothesis:'Municipal and public operators need better coverage, utilization, and rider visibility without rebuilding the full technology stack. SWVL can provide a configurable mobility platform and operational analytics.',signals:'Transit tender · underserved zone · digitization program · fleet renewal · sustainability mandate',buyers:'Transit Director · CIO · Operations · Planning · Procurement',proof:'SaaS platform · demand analysis · network planning · real-time operations'}
};
const ids={priority:'segment-priority',title:'segment-title',hypothesis:'segment-hypothesis',signals:'segment-signals',buyers:'segment-buyers',proof:'segment-proof'};
document.querySelectorAll('.segment-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.segment-tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');const data=segments[btn.dataset.segment];Object.entries(ids).forEach(([key,id])=>document.getElementById(id).textContent=data[key]);}));
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const selected=btn.dataset.filter;document.querySelectorAll('.timeline article').forEach(card=>card.classList.toggle('hidden',selected!=='all'&&card.dataset.channel!==selected));}));
const weights={data:.25,reply:.25,held:.2,sqo:.3};
function updateScore(){const values={};document.querySelectorAll('[data-score]').forEach(input=>{values[input.dataset.score]=Number(input.value);document.getElementById('out-'+input.dataset.score).textContent=input.value+'%'});const normalized={data:values.data,reply:Math.min(values.reply*5,100),held:values.held,sqo:values.sqo};const score=Math.round(Object.keys(weights).reduce((sum,k)=>sum+normalized[k]*weights[k],0));document.getElementById('score-value').textContent=score;const ring=document.getElementById('score-ring');ring.style.transform=`rotate(${Math.max(-8,Math.min(8,(score-50)/7))}deg)`;let title='Build the foundation',advice='Start with account data quality and a clear segment hypothesis before adding more activity.';if(score>=45){title='Fix the conversion handoff';advice='Targeting is workable, but discovery quality and AE handoff need a tighter definition of qualified.'}if(score>=70){title='Scale the winning plays';advice='The engine is healthy. Increase coverage inside proven segments and protect quality as volume grows.'}if(score>=86){title='Compound the advantage';advice='Strong readiness. Focus on experiment velocity, expansion signals, and pipeline efficiency by segment.'}document.getElementById('score-title').textContent=title;document.getElementById('score-advice').textContent=advice}
document.querySelectorAll('[data-score]').forEach(input=>input.addEventListener('input',updateScore));updateScore();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'none'}],{duration:500,easing:'ease-out',fill:'both'})}),{threshold:.08});document.querySelectorAll('section>div,section>h2,.pillar,.timeline article').forEach(el=>observer.observe(el));
